name: My First WorkFlow

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
  
            - name: list and cat
              run: |
                echo "my first github actions from runner"
                ls
                cat README.md
            - name: Generate ASCII report
              run: cowsay -f dragon  "I am the dragon reborn " >> dragon.txt