name: My First WorkFlow

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome message
              run: echo "my first github actions from runner"

            - name: list files
              run: ls

            - name: reading a file
              run: cat README.md
