name: Definig mutiple jobs

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install cowsay
      run: |
        sudo apt -y install cowsay -y 
        cowsay -f dragon "Im the dragon reboirn" >> dragon.txt
    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: dragon file
        path: dragon.txt

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
    - name: checkout    
      uses: actions/checkout@v4
    - name: download-artifact
      uses: actions/download-artifact@v4
      with:
          name: dragon file
    - name: list and cat
      run: |
        echo "my first github actions from runner"
        ls
        cat dragon.txt
    - name: download-artifact
      uses: actions/download-artifact@v4
      with:
          name: dragon file

  


  deploy_test:
    needs: [test_job]
    runs-on: ubunt-latest      
    steps:
      - name: checkout    
        uses: actions/checkout@v4

      - name: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon file
    
      - name: list and cat
        run: |
          echo "my first github actions from runner"
          ls
          cat README.md

