name: My Matrix config file

on: 
    push:
    workflow_dispatch:

jobs:
  deploy-on-ubunu:
    runs-on: ubuntu-latest
    steps:
    - name: docker on ubuntu
      run: docker info

    - name: docker images
      run: docker run hello-world

  deploy-on-windows:
     runs-on: windows-latest
     steps:
     - name: docker on windows
       run: docker info
        



      
