name: My shell script run

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: change permission
      run: |
        chmod 755 sample.sh
        ./sample.sh
