name: My shell script run

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: list and cat
      run: |
        chmod 755 myscript.sh
        ./myscript.sh
